from collections.abc import Awaitable
from pathlib import Path

__version__: str

class DataError(Exception): ...
class InvalidInputError(DataError): ...
class InvalidResponseError(DataError): ...
class HttpError(DataError): ...
class TimeoutError(DataError): ...
class SizeLimitError(DataError): ...
class ConversionError(DataError): ...
class IoError(DataError): ...
class CancelledError(DataError): ...

class Table:
    @property
    def name(self) -> str: ...
    @property
    def num_rows(self) -> int: ...
    def schema_json(self) -> str: ...
    def write(self, path: str | Path, format: str) -> None: ...
    def write_parquet(self, path: str | Path) -> None: ...
    def write_csv(self, path: str | Path) -> None: ...
    def write_ipc(self, path: str | Path) -> None: ...
    def __arrow_c_schema__(self) -> object: ...
    def __arrow_c_stream__(self, requested_schema: object | None = None) -> object: ...

class TableSet:
    def keys(self) -> list[str]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, name: str) -> Table: ...
    def write_dir(self, path: str | Path, format: str = "parquet") -> None: ...

class _RoCrate:
    def __init__(self, source: bytes) -> None: ...
    @staticmethod
    def from_path(path: str) -> _RoCrate: ...
    def metadata_json(self) -> str: ...
    def types(self) -> list[str]: ...
    def entity_json(self, identifier: str) -> str | None: ...
    def name(self, fallback: str) -> str: ...
    def infer_config_json(self) -> str: ...
    def to_tables(
        self, types: list[str] | None = None, config: str | None = None
    ) -> TableSet: ...
    def wordflow_table(self, identifier: str, config: str | None = None) -> Table: ...
    def documents_json(self) -> str: ...

class _ByteStream:
    def next_chunk(self) -> bytes | None: ...
    def next_chunk_async(self) -> Awaitable[bytes | None]: ...
    def close(self) -> None: ...

class _Client:
    def __init__(
        self,
        api_key: str | None,
        base_url: str,
        timeout: float,
        max_json_bytes: int,
        max_document_bytes: int,
        concurrency: int,
        max_documents: int,
    ) -> None: ...
    def with_api_key(self, key: str | None) -> _Client: ...
    def close(self) -> None: ...
    def call(self, operation: str, args: str) -> str: ...
    def call_async(self, operation: str, args: str) -> Awaitable[str]: ...
    def document_table(
        self, identifier: str, paths: list[str], max_total_bytes: int
    ) -> Table: ...
    def document_table_async(
        self, identifier: str, paths: list[str], max_total_bytes: int
    ) -> Awaitable[Table]: ...
    def open_stream(
        self, identifier: str, path: str, max_bytes: int
    ) -> _ByteStream: ...
    def open_stream_async(
        self, identifier: str, path: str, max_bytes: int
    ) -> Awaitable[_ByteStream]: ...
    def wordflow_table(
        self, identifier: str, crate: _RoCrate, max_total_bytes: int
    ) -> Table: ...
    def wordflow_table_async(
        self, identifier: str, crate: _RoCrate, max_total_bytes: int
    ) -> Awaitable[Table]: ...

def extract_identifier(value: str) -> str | None: ...
def normalize_jsonld(value: str) -> str: ...
def search_body(method: str, query: str, limit: int, offset: int) -> str: ...
def wordflow_config(identifier: str) -> str: ...
