import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { saveBackendDownload, saveBlob } from './download';

const originalCreateObjectURL = URL.createObjectURL;
const originalRevokeObjectURL = URL.revokeObjectURL;

const mocks = vi.hoisted(() => ({
  invoke: vi.fn(),
  isTauri: vi.fn(),
  getCsrfToken: vi.fn(),
  revealItemInDir: vi.fn(),
  toast: { error: vi.fn(), success: vi.fn() },
}));

vi.mock('@tauri-apps/api/core', () => ({ invoke: mocks.invoke }));
vi.mock('@tauri-apps/plugin-opener', () => ({ revealItemInDir: mocks.revealItemInDir }));
vi.mock('@/lib/backend/csrfToken', () => ({ getCsrfToken: mocks.getCsrfToken }));
vi.mock('@/lib/isTauri', () => ({ isTauri: mocks.isTauri }));
vi.mock('sonner', () => ({ toast: mocks.toast }));

describe('desktop download boundary', () => {
  afterEach(() => {
    vi.restoreAllMocks();
    vi.useRealTimers();
    URL.createObjectURL = originalCreateObjectURL;
    URL.revokeObjectURL = originalRevokeObjectURL;
  });

  beforeEach(() => {
    vi.clearAllMocks();
    mocks.isTauri.mockReturnValue(true);
    mocks.getCsrfToken.mockReturnValue('desktop-csrf');
    mocks.invoke.mockImplementation(async (command: string) =>
      command === 'save_backend_download'
        ? {
            fullPath: '/Users/test/Documents/result.bin',
            omittedTabCount: 0,
            omittedAnalysisCount: 0,
          }
        : '/Users/test/Documents/result.bin',
    );
    URL.createObjectURL = vi.fn(() => 'blob:download');
    URL.revokeObjectURL = vi.fn();
  });

  it('sends webview-generated bytes to the native saver', async () => {
    await saveBlob(new Blob(['payload']), 'result.bin');

    expect(mocks.invoke).toHaveBeenCalledWith('save_generated_bytes', {
      filename: 'result.bin',
      bytes: new Uint8Array([112, 97, 121, 108, 111, 97, 100]),
    });
  });

  it('treats a cancelled generated-artifact chooser as cancellation', async () => {
    mocks.invoke.mockResolvedValueOnce(null);
    expect(await saveBlob(new Blob(['payload']), 'result.bin')).toBe(false);
    expect(mocks.toast.success).not.toHaveBeenCalled();
    expect(mocks.toast.error).not.toHaveBeenCalled();
  });

  it('retains browser-owned downloads without invoking Rust', async () => {
    vi.useFakeTimers();
    mocks.isTauri.mockReturnValue(false);
    const click = vi
      .spyOn(HTMLAnchorElement.prototype, 'click')
      .mockImplementation(() => undefined);
    const loadBrowserDownload = vi.fn().mockResolvedValue({
      blob: new Blob(['browser']),
      filename: 'collection/server.csv',
      omittedTabCount: 2,
      omittedAnalysisCount: 3,
    });

    const omissions = await saveBackendDownload('/api/export', 'fallback.csv', loadBrowserDownload);

    expect(loadBrowserDownload).toHaveBeenCalledTimes(1);
    expect(click).toHaveBeenCalledTimes(1);
    const anchor = click.mock.instances[0] as HTMLAnchorElement;
    expect(anchor.download).toBe('server.csv');
    expect(anchor.href).toBe('blob:download');
    expect(mocks.invoke).not.toHaveBeenCalled();
    expect(omissions).toEqual({ omittedTabCount: 2, omittedAnalysisCount: 3 });
    await vi.runAllTimersAsync();
    expect(URL.revokeObjectURL).toHaveBeenCalledWith('blob:download');
    expect(anchor.isConnected).toBe(false);
  });
});
